[[constraint]]
  version = "kubernetes-1.14.2"
  name = "k8s.io/apiextensions-apiserver"

[[constraint]]
  version = "kubernetes-1.14.2"
  name = "k8s.io/apimachinery"

[prune]
  go-tests = true
  unused-packages = true
